### PR TITLE
Small presentation changes

### PR DESCRIPTION
**Pull request by Dasonk**
I made two/three small changes that I think make some things either more aesthetically pleasing or clarify what the label actually means.

### CODE REVIEW

**Comment by simon-weber** [comment]
Thanks! Will cut a release for this in the next day or two.

**Comment by simon-weber** [comment]
These are going out now in 5.1.6.

**Comment by Dasonk** [comment]
How does one go about getting a developer license for this? I'm not sure my tiny contribution so far would qualify and I'd be more than happy to throw a few dollars your way but I also want to be able to contribute more since I've moved away from Spotify and am using google music almost exclusively these days.  I mean I can run it locally and spoof having a full license but I'd also like to do things the proper way so I don't have to undo any of those shady changes to get around the license check if/when I want to submit a pull request.

**Comment by simon-weber** [comment]
Haha, sure. Shoot me an email and I'll get you hooked up: simon@simonmweber.com.

**Pull request merged**
